
export const nigerianBanks = [
  'Access Bank', 'First Bank', 'GTBank', 'Zenith Bank', 'UBA', 'Fidelity Bank',
  'Sterling Bank', 'Union Bank', 'Wema Bank', 'FCMB', 'Heritage Bank',
  'Keystone Bank', 'Polaris Bank', 'Stanbic IBTC', 'Standard Chartered',
  'Unity Bank', 'Providus Bank', 'Jaiz Bank', 'SunTrust Bank', 'Titan Trust Bank',
  'Globus Bank', 'Parallex Bank', 'Premium Trust Bank', 'Optimus Bank',
  'Moniepoint MFB', 'Kuda Bank', 'Opay', 'PalmPay', 'Carbon', 'Rubies Bank',
  'Mint MFB', 'Sparkle MFB', 'Renmoney MFB', 'LAPO MFB', 'AB MFB',
  'Accion MFB', 'Above Only MFB', 'Adeyemi College Staff MFB', 'Aelex MFB',
  'Afekhafe MFB', 'Agosasa MFB', 'Ahmadu Bello University MFB', 'Ajaokuta Steel MFB',
  'Akwa United MFB', 'Alekun MFB', 'Alvana MFB', 'Amju Unique MFB',
  'Assetmatrix MFB', 'Baines Credit MFB', 'Bowen MFB', 'Branch MFB',
  'Citi MFB', 'Corestep MFB', 'Daylight MFB', 'Dot MFB',
  'Ekimogun MFB', 'Finca MFB', 'Gateway MFB', 'Greenbank MFB',
  'Hackman MFB', 'Hasal MFB', 'Ibile MFB', 'Ikoyi Osborn MFB',
  'Imowo MFB', 'Infinity MFB', 'Kredi Money MFB', 'Lagos Building MFB',
  'Links MFB', 'Living Trust MFB', 'Lovonus MFB', 'Mainstreet MFB',
  'Mkobo MFB', 'NPF MFB', 'Okpoga MFB', 'Page MFB',
  'Parkway MFB', 'Peace MFB', 'Personal Trust MFB', 'Petra MFB',
  'Purplemoney MFB', 'Regent MFB', 'Relief MFB', 'Royal Exchange MFB',
  'Safe Haven MFB', 'Seedvest MFB', 'Stellas MFB', 'TCF MFB',
  'Unaab MFB', 'Unical MFB', 'VFD MFB', 'Visa MFB',
  'Virtue MFB', 'Wetland MFB', 'Xslnce MFB', 'Yes MFB'
];
